<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	  <PackageId>NugetClass.Generico</PackageId>
	  <Version>1.0.0</Version>
	  <Authors>Roberto Toloza Mendoza</Authors>
	  <Description>Paginación genérica con filtro dinámico reutilizable.</Description>  
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.19" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.4" />
  </ItemGroup>

</Project>
